### PR TITLE
DCM-138 Added no cache and redirect if in invalid state

### PR DESCRIPTION
**Pull request by froberg**

### CODE REVIEW

**Comment by froberg** [comment]
Is this ok?
- Redirect user to 'start page' if not in valid state.
- Almost no pages has cache turned on
- Need text and style for message

Probably should look at Employer as well?
/c

**Comment by leewadhams** [comment]
@froberg from a very quick look it looks good. Lets walk-through it tomorrow morning.

**Comment by froberg** [comment]
Hey @rajeshdigital 
Can you style the message box in the file ***SFA.DAS.ProviderApprenticeshipsService.Web\Views\Account\Index.cshtml**
I can explain when you have time to do it. 
/c

**Comment by froberg** [comment]
@rajeshdigital do you need anything else for this story?
I have added *_InvalidState.cshtml*.

**Comment by froberg** [comment]
@rajeshdigital - This story (in jira) is in ReadyForTest but the pull request is still open.
Do you know anything about that?
/c

**Comment by froberg** [comment]
@leewadhams 
This was never merged so that's why the bug.
Can you have a look at it?
/c

**Comment by chrisfoster76** [comment]
@leewadhams @froberg I have brought this branch up to date with master. It wasn't a very pleasant merge as the branch was a month old. Could you take a look?

**Pull request merged**
